version: "3.3"

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - api
    volumes:
      - ./nginx/production/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    restart: always

  api:
    image: socialhub_api
    depends_on:
      - db
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      SECRET_STRING_FILE: /run/secrets/secret_string
      ASPNETCORE_ENVIRONMENT: Production
    secrets:
      - db_user
      - db_password
      - secret_string
    restart: always

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: SocialHub
    secrets:
      - db_user
      - db_password
      - secret_string
    restart: always

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  secret_string:
    file: ./secrets/secret_string.txt
