version: "3.3"

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443

  api:
    build:
      context: .
      dockerfile: Dockerfile.API
    depends_on:
      - db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      SECRET_STRING: SuperSecretString
      ASPNETCORE_ENVIRONMENT: Development

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: SocialHub
